{
  subvars,
  config,
  ...
}: {
  # Don't allow mutation of users outside the config.
  users.mutableUsers = false;

  users.groups = {
    "${subvars.username}" = {};
    docker = {};
    wireshark = {};
    # misc
    uinput = {};
  };

  users.users."${subvars.username}" = {
    # generated by `mkpasswd -m scrypt`
    # we have to use initialHashedPassword here when using tmpfs for /
    inherit (subvars) initialHashedPassword;
    home = "/home/${subvars.username}";
    isNormalUser = true;
    extraGroups = [
      subvars.username
      "users"
      "networkmanager"
      "wheel"
      "docker"
      "wireshark"
      "libvirtd"
    ];
  };

  # root's ssh key are mainly used for remote deployment
  users.users.root = {
    initialHashedPassword = config.users.users."${subvars.username}".initialHashedPassword;
    openssh.authorizedKeys.keys = config.users.users."${subvars.username}".openssh.authorizedKeys.keys;
  };
}